version: '3'

dotenv: ['account.env']

tasks:
  build:
    cmds:
      - cargo near build --no-docker
  test:
    cmds:
      - cargo test
  format-code:
    aliases: ["fc"]
    cmds:
      - cargo fmt --all
  check-code:
    aliases: ["cc"]
    cmds:
      - cargo fmt --all -- --check
      - cargo clippy --all-targets --all-features -- -D warnings
  deploy:
    cmds:
      - if [ ! -f ./account.env ]; then task create-account; fi
      - cargo near deploy --no-docker $CONTACT_NAME without-init-call network-config testnet sign-with-keychain send
      - echo "Deployed! ðŸŽ‰"
      - task get-account

  get-account:
    aliases: ["ga"]
    cmds:
      - echo "Near contact account $CONTACT_NAME ðŸ“„:"
      - echo "Explore https://testnet.nearblocks.io/address/$CONTACT_NAME ðŸŒ"

  create-account:
    aliases: ["ca"]
    vars:
      BRANCH: $(git rev-parse --abbrev-ref HEAD)
      COMMIT: $(git rev-parse --short HEAD)
      ACCOUNT_ID: $(echo berry-{{.COMMIT}}-{{.BRANCH}}.testnet)
    cmds:
      - cmd: near account create-account sponsor-by-faucet-service {{.ACCOUNT_ID}} autogenerate-new-keypair save-to-keychain network-config testnet create
        ignore_error: true
      - echo CONTACT_NAME={{.ACCOUNT_ID}} > account.env
      - echo Created account {{.ACCOUNT_ID}} âž•
