name: Build contract

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
      - "dev"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install deps
      - run: npm i

      - name: Build
      - run: npm run build

      - name: Test
      - run: npm run test
