name: Build contract

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
      - "dev"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contract

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup contract
        working-directory: ./app
        run:

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
